# Generated by Django 4.2.4 on 2023-08-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KomodoreApp', '0002_rename_companyname_company_companyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Batteries', 'Batteries'), ('Engine Oil', 'Engine Oil'), ('Antifreeze', 'Antifreeze'), ('Fuel Lines', 'Fuel Lines'), ('Exhaust', 'Exhaust'), ('Windshield Wipers', 'Windshield Wipers'), ('Brakes', 'Brakes'), ('Engine Parts', 'Engine Parts'), ('Tires', 'Tires'), ('Wheel Mountings', 'Wheel Mountings')], default='Batteries', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.CharField(choices=[('No Warranty', 'No Warranty'), ('1 Year Warranty', '1 Year Warranty'), ('2 Year Warranty', '2 Year Warranty'), ('Lifetime Warranty', 'Lifetime Warranty')], max_length=100),
        ),
    ]
