# Generated by Django 4.2.4 on 2023-08-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KomodoreApp', '0003_product_category_product_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
